[build]
  command = "npm run build"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.6.7"

# Redireciona todas as requisições não encontradas para index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
